# Robot Sim Config
# Copyright (c) 2019 FRC Team 3260

controller:
  ip: "127.0.0.1"   # IP address where controller is running
  port: 8000        # Port where controller is running

sim:
  ip: "127.0.0.1"   # IP address where sim is running
  port: 4000        # Port where sim is running

elevator:
  belt:
    radius: 0.02    # Meters
    width: 0.02     # Meters
    length: 0.3     # Meters
  motorShaft:
    radius: 0.005   # Meters
    length: 0.03    # Meters
  motor:
    radius: 0.015   # Meters
    length: 0.03    # Meters
    maxSpeed: 10    # RPM
  encoder:
    radius: 0.01    # Meters
    length: 0.003   # Meters
  carriage:
    lengthX: 0.001  # Meters
    lengthY: 0.03   # Meters
    lengthZ: 0.02   # Meters
