# Robot Config
# Copyright (c) 2019 FRC Team 3260

joystick:
  ip: "127.0.0.1"        # IP address where joystick is running
  port: 2000             # Port where joystick is running

core:
  ip: "127.0.0.1"        # IP address where core is running
  joystickPort: 4000     # Port where joystick should send its commands
  vehiclePort: 6000      # Port where vehicle should send its state

vehicle:
  ip: "127.0.0.1"        # IP address where sim is running
  port: 8000             # Port where sim is running
  constants:
    drivetrain:
      width: 27.5        # Inches, length along robot's y-axis
      depth: 28.3        # Inches, length along robot's x-axis
      widthChannel: 0.5  # Inches
      heightChannel: 0.5 # Inches
      wheelBase: 18      # Inches, distance between centers of front and rear wheels
      wheelRadius: 2.0   # Inches
      wheelWidth: 1.0    # Inches
      motor:
        maxSpeed: 500    # RPM
    elevator:
      belt:
        radius: 0.02     # Meters
        width: 0.2       # Meters
        length: 1.0      # Meters
      motorShaft:
        radius: 0.005    # Meters
        length: 0.03     # Meters
      motor:
        radius: 0.015    # Meters
        length: 0.03     # Meters
        maxSpeed: 500    # RPM
      encoder:
        radius: 0.01     # Meters
        length: 0.003    # Meters
      carriage:
        lengthX: 0.1     # Meters
        lengthY: 0.2     # Meters
        lengthZ: 0.001   # Meters
  initialState:
    drivetrain:
      x: 0
      y: 0
    elevator:
      motorSpeed: 0      # RPM (-motor.maxSpeed to +motor.maxSpeed)
      carriagePos: 0     # Meters (0 to belt.length)
