# Robot Config
# Copyright (c) 2019 FRC Team 3260

joystick:
  ip: "127.0.0.1"      # IP address where joystick is running
  port: 2000           # Port where joystick is running

controls:
  ip: "127.0.0.1"      # IP address where controls are running
  port: 6000           # Port where controls are running

vehicle:
  ip: "127.0.0.1"      # IP address where sim is running
  port: 8000           # Port where sim is running
  constants:
    elevator:
      belt:
        radius: 0.02   # Meters
        width: 0.02    # Meters
        length: 0.3    # Meters
      motorShaft:
        radius: 0.005  # Meters
        length: 0.03   # Meters
      motor:
        radius: 0.015  # Meters
        length: 0.03   # Meters
        maxSpeed: 500  # RPM
      encoder:
        radius: 0.01   # Meters
        length: 0.003  # Meters
      carriage:
        lengthX: 0.001 # Meters
        lengthY: 0.03  # Meters
        lengthZ: 0.02  # Meters
  initialState:
    elevator:
      motorSpeed: 0    # RPM (-motor.maxSpeed to +motor.maxSpeed)
      carriagePos: 0   # Meters (0 to belt.length)
