# Robot Config
# Copyright (c) 2020 FRC Team 3260

joystick:
  ip: "127.0.0.1"                                        # IP address where joystick is running
  port: 2000                                             # Port where core should send its status

core:
  ip: "127.0.0.1"                                        # IP address where core is running
  joystickPort: 4000                                     # Port where joystick should send its commands
  vehiclePort: 6000                                      # Port where vehicle should send its state

sim:
  comms:
    ip: "127.0.0.1"                                      # IP address where sim is running
    port: 8000                                           # Port where vehicle should send its commands
  assets:
    fieldModelFile: "/data/models/field2020.wrl"         # Path to 3D WRL model of the field
    vehicleModelFile: "/data/models/vehicle2020.wrl"     # Path to 3D WRL model of the vehicle
    gamePieceModelFile: "/data/models/gamepiece2020.wrl" # Path to 3D WRL model of the game piece
    fontFile: "/data/fonts/helvetica.ttf"                # Path to font file for HUD text
  field:
    exteriorPolygon:                                     # Exterior wall
      - { x: 161.81, y: 288.58 }
      - { x: 90.94, y: 314.96 }
      - { x: -90.94, y: 314.96 }
      - { x: -161.81, y: 288.58 }
      - { x: -161.81, y: -288.58 }
      - { x: -90.94, y: -314.96 }
      - { x: 90.94, y: -314.96 }
      - { x: 161.81, y: -288.58 }
    interiorPolygons:
      -                                                  # Right trench right wall
        - { x: 161.81, y: -59.84 }
        - { x: 161.81, y: -29.92 }
        - { x: 159.84, y: -29.92 }
        - { x: 159.84, y: -59.84 }
      -                                                  # Right trench left wall
        - { x: 107.48, y: -59.84 }
        - { x: 107.48, y: -29.92 }
        - { x: 105.51, y: -29.92 }
        - { x: 105.51, y: -59.84 }
      -                                                  # Left trench right wall
        - { x: -159.84, y: 29.92 }
        - { x: -159.84, y: 59.84 }
        - { x: -161.81, y: 59.84 }
        - { x: -161.81, y: 29.92 }
      -                                                  # Left trench left wall
        - { x: -105.51, y: 29.92 }
        - { x: -105.51, y: 59.84 }
        - { x: -107.48, y: 59.84 }
        - { x: -107.48, y: 29.92 }
      -                                                  # Right column
        - { x: 105.12, y: -47.64 }
        - { x: 100.39, y: -36.61 }
        - { x: 89.37, y: -41.34 }
        - { x: 94.09, y: -52.36 }
      -                                                  # Top column
        - { x: 44.88, y: 97.64 }
        - { x: 40.55, y: 108.27 }
        - { x: 29.53, y: 103.54 }
        - { x: 33.86, y: 92.52 }
      -                                                  # Left column
        - { x: -89.37, y: 41.34 }
        - { x: -94.09, y: 52.36 }
        - { x: -105.12, y: 47.64 }
        - { x: -100.39, y: 36.61 }
      -                                                  # Bottom column
        - { x: -29.53, y: -103.54 }
        - { x: -33.86, y: -92.52 }
        - { x: -44.88, y: -96.85 }
        - { x: -40.55, y: -108.27 }
  vehicle:
    polygon:                                             # Bounding polygon (meters where (0, 0) is the center of rotation of the robot)
      - { x: 16.93, y: 12.2 }
      - { x: -13.78, y: 12.2 }
      - { x: -13.78, y: -12.2 }
      - { x: 16.93, y: -12.2 }
    weight: 154                                          # Pounds
    initialState:
      x: 0                                               # Inches
      y: -197.0                                          # Inches
      theta: 90                                          # Degrees
    drivetrain:
      width: 27.5                                        # Inches, length along robot's y-axis
      depth: 28.3                                        # Inches, length along robot's x-axis
      widthChannel: 0.5                                  # Inches
      heightChannel: 0.5                                 # Inches
      wheelBase: 18                                      # Inches, distance between centers of front and rear wheels
      wheelRadius: 3.0                                   # Inches
      wheelWidth: 1.0                                    # Inches
      leftMotorMaxSpeed: 833                             # RPM
      rightMotorMaxSpeed: 833                            # RPM
    intake:
      centerMotorMaxSpeed: 50                            # RPM
      leftMotorMaxSpeed: 50                              # RPM
      rightMotorMaxSpeed: 50                             # RPM
  gamePiece:
    radius: 3.50                                         # Inches
    initialPositions:                                    # Inches (where (0, 0) is the center of the field)
      - { x: 47.24, y: 64.17 }
      - { x: 40.94, y: 79.53 }
      - { x: 16.54, y: 86.61 }
      - { x: 1.18, y: 80.31 }
      - { x: -14.17, y: 74.02 }
      - { x: -47.24, y: -64.17 }
      - { x: -40.94, y: -79.53 }
      - { x: -16.54, y: -86.61 }
      - { x: -1.18, y: -80.31 }
      - { x: 14.17, y: -74.02 }
      - { x: 142.91, y: -64.17 }
      - { x: 124.41, y: -64.17 }
      - { x: 133.86, y: 0.0 }
      - { x: 133.86, y: 35.83 }
      - { x: 133.86, y: 72.05 }
      - { x: -142.91, y: 64.17 }
      - { x: -124.41, y: 64.17 }
      - { x: -133.86, y: -0.0 }
      - { x: -133.86, y: -35.83 }
      - { x: -133.86, y: -72.05 }
