# Robot Config
# Copyright (c) 2019 FRC Team 3260

joystick:
  ip: "127.0.0.1"        # IP address where joystick is running
  port: 2000             # Port where core should send its status

core:
  ip: "127.0.0.1"        # IP address where core is running
  joystickPort: 4000     # Port where joystick should send its commands
  vehiclePort: 6000      # Port where vehicle should send its state

vehicle:
  ip: "127.0.0.1"        # IP address where sim is running
  port: 8000             # Port where vehicle should send its commands
  constants:
    drivetrain:
      width: 27.5        # Inches, length along robot's y-axis
      depth: 28.3        # Inches, length along robot's x-axis
      widthChannel: 0.5  # Inches
      heightChannel: 0.5 # Inches
      wheelBase: 18      # Inches, distance between centers of front and rear wheels
      wheelRadius: 2.0   # Inches
      wheelWidth: 1.0    # Inches
      motor:
        maxSpeed: 500    # RPM
    elevator:
      belt:
        radius: 0.79     # Inches
        width: 7.87      # Inches
        length: 39.37    # Inches
      motorShaft:
        radius: 0.2      # Inches
        length: 1.18     # Inches
      motor:
        radius: 0.59     # Inches
        length: 1.18     # Inches
        maxSpeed: 500    # RPM
      encoder:
        radius: 0.39     # Inches
        length: 0.12     # Inches
      carriage:
        lengthX: 3.94    # Inches
        lengthY: 7.87    # Inches
        lengthZ: 0.04    # Inches
  initialState:
    drivetrain:
      x: 0
      y: 0
    elevator:
      motorSpeed: 0     # RPM (-motor.maxSpeed to +motor.maxSpeed)
      carriagePos: 0    # Inches (0 to belt.length)
